// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feniybfjbvhjrjubigbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbml5YmZqYnZoanJqdWJpZ2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDMwMjAsImV4cCI6MjA2MjQ3OTAyMH0.dXr1SSMbsSznsMMtKMa7bo06o8vd_S2wdhMQyz3IyMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);